// | #  | Genre Diversity | Track Popularity | Artist Consistency | Era | Valence  | Arousal   | Persona Name                    | Description                                                                                  | Theme (Color)   |
// | -- | --------------- | ---------------- | ------------------ | --- | -------- | --------- | ------------------------------- | -------------------------------------------------------------------------------------------- | --------------- |
// | 1  | High            | High             | High               | New | Positive | Energetic | **The Trend Voyager**           | Explores modern hits across genres but sticks to favorite stars. Loves energy and discovery. | Neon cyan       |
// | 2  | High            | High             | High               | New | Positive | Calm      | **The Chill Curator**           | Enjoys diverse modern hits but prefers smooth, relaxed sounds.                               | Soft mint       |
// | 3  | High            | High             | High               | New | Negative | Energetic | **The Electric Escapist**       | Channels emotion through upbeat new tracks across many genres.                               | Magenta red     |
// | 4  | High            | High             | High               | New | Negative | Calm      | **The Reflective Dreamer**      | Listens to melancholy modern hits with genre variety but emotional depth.                    | Misty blue      |
// | 5  | High            | High             | High               | Old | Positive | Energetic | **The Golden Revivalist**       | Reignites classic hits from many eras, full of nostalgia and rhythm.                         | Gold            |
// | 6  | High            | High             | High               | Old | Positive | Calm      | **The Vintage Enthusiast**      | Savors diverse old classics in a mellow, reflective mood.                                    | Antique cream   |
// | 7  | High            | High             | High               | Old | Negative | Energetic | **The Restless Romantic**       | Draws passion from the drama and energy of timeless tracks.                                  | Deep crimson    |
// | 8  | High            | High             | High               | Old | Negative | Calm      | **The Sentimental Archivist**   | Immersed in melancholic golden-age hits, finding comfort in the past.                        | Sepia brown     |
// | 9  | High            | High             | Low                | New | Positive | Energetic | **The Playlist Hopper**         | Constantly jumps through upbeat, popular new music—always chasing the next vibe.             | Hot pink        |
// | 10 | High            | High             | Low                | New | Positive | Calm      | **The Easy Explorer**           | Samples fresh chart-toppers lightly; easygoing and mood-driven.                              | Peach           |
// | 11 | High            | High             | Low                | New | Negative | Energetic | **The Chaos Seeker**            | Finds catharsis in energetic, emotionally charged new hits.                                  | Scarlet         |
// | 12 | High            | High             | Low                | New | Negative | Calm      | **The Moody Mixer**             | A quiet drifter between sad, modern playlists and chill genres.                              | Slate blue      |
// | 13 | High            | High             | Low                | Old | Positive | Energetic | **The Retro Nomad**             | Dances between upbeat golden tracks of every genre.                                          | Burnt orange    |
// | 14 | High            | High             | Low                | Old | Positive | Calm      | **The Gentle Nostalgic**        | Enjoys soft classic hits from varied genres with easy warmth.                                | Sand beige      |
// | 15 | High            | High             | Low                | Old | Negative | Energetic | **The Haunted DJ**              | Replays intense, emotional classics to relive the fire of the past.                          | Deep wine       |
// | 16 | High            | High             | Low                | Old | Negative | Calm      | **The Fading Wanderer**         | Wanders through wistful old tunes, lost in gentle melancholy.                                | Dusty gray      |
// | 17 | High            | Low              | High               | New | Positive | Energetic | **The Indie Devotee**           | Loyal to select modern indie artists with high energy and spirit.                            | Violet          |
// | 18 | High            | Low              | High               | New | Positive | Calm      | **The Ambient Collector**       | Focused on calm, experimental modern sounds and sonic craftsmanship.                         | Soft teal       |
// | 19 | High            | Low              | High               | New | Negative | Energetic | **The Subculture Rebel**        | Loyal to raw, underground acts that vent emotion and truth.                                  | Blood red       |
// | 20 | High            | Low              | High               | New | Negative | Calm      | **The Shadow Curator**          | Devoted to mellow, somber modern soundscapes from niche artists.                             | Charcoal blue   |
// | 21 | High            | Low              | High               | Old | Positive | Energetic | **The Vintage Explorer**        | Travels through upbeat forgotten gems of old music.                                          | Copper          |
// | 22 | High            | Low              | High               | Old | Positive | Calm      | **The Gentle Historian**        | Studies obscure classics for serenity and craft.                                             | Faded gold      |
// | 23 | High            | Low              | High               | Old | Negative | Energetic | **The Underground Romantic**    | Channels emotion through rare, passionate old songs.                                         | Rust red        |
// | 24 | High            | Low              | High               | Old | Negative | Calm      | **The Obscure Archivist**       | Carefully collects somber, forgotten treasures of the past.                                  | Deep brown      |
// | 25 | High            | Low              | Low                | New | Positive | Energetic | **The Sonic Wanderer**          | Skims new underground energy scenes for fun and freedom.                                     | Turquoise       |
// | 26 | High            | Low              | Low                | New | Positive | Calm      | **The Modern Daydreamer**       | Casual listener drifting through niche calm sounds.                                          | Sky blue        |
// | 27 | High            | Low              | Low                | New | Negative | Energetic | **The Noise Nomad**             | Energetic seeker of emotional chaos in experimental new sounds.                              | Neon red        |
// | 28 | High            | Low              | Low                | New | Negative | Calm      | **The Fadeaway Listener**       | Soft, sad traveler through underground mellow genres.                                        | Cloud gray      |
// | 29 | High            | Low              | Low                | Old | Positive | Energetic | **The Eclectic Retrohead**      | Mixes lively, underappreciated old tracks across scenes.                                     | Amber           |
// | 30 | High            | Low              | Low                | Old | Positive | Calm      | **The Vinyl Drifter**           | Plays gentle, obscure classics for peaceful reflection.                                      | Cream           |
// | 31 | High            | Low              | Low                | Old | Negative | Energetic | **The Obscure Punk**            | Intense dive into forgotten, emotional old underground.                                      | Dark crimson    |
// | 32 | High            | Low              | Low                | Old | Negative | Calm      | **The Lost Listener**           | Softly nostalgic and withdrawn, cherishing emotional old sounds.                             | Muted gray      |
// | 33 | Low             | High             | High               | New | Positive | Energetic | **The Pop Loyalist**            | Faithful to upbeat, mainstream modern icons.                                                 | Hot pink        |
// | 34 | Low             | High             | High               | New | Positive | Calm      | **The Chart Regular**           | Listens loyally to smooth new pop favorites for relaxation.                                  | Light rose      |
// | 35 | Low             | High             | High               | New | Negative | Energetic | **The Modern Melancholic**      | Draws emotional fire from popular yet dark-tinged modern music.                              | Magenta red     |
// | 36 | Low             | High             | High               | New | Negative | Calm      | **The Brooding Fan**            | Listens to emotional, reflective pop favorites quietly.                                      | Dusky violet    |
// | 37 | Low             | High             | High               | Old | Positive | Energetic | **The Classic Loyalist**        | Passionate about golden-age hits, played with joy and devotion.                              | Bright gold     |
// | 38 | Low             | High             | High               | Old | Positive | Calm      | **The Vintage Devotee**         | Finds comfort in familiar old classics from a few beloved artists.                           | Pale tan        |
// | 39 | Low             | High             | High               | Old | Negative | Energetic | **The Dramatic Traditionalist** | Relives the emotional power of intense, old hits.                                            | Deep burgundy   |
// | 40 | Low             | High             | High               | Old | Negative | Calm      | **The Melancholy Purist**       | Listens to soft, sorrowful classics on repeat.                                               | Dusty brown     |
// | 41 | Low             | High             | Low                | New | Positive | Energetic | **The Mainstream Hopper**       | Always chasing the next upbeat hit without attachment.                                       | Bright yellow   |
// | 42 | Low             | High             | Low                | New | Positive | Calm      | **The Easy Listener**           | Casual with new pop hits, enjoys a relaxed routine.                                          | Pastel pink     |
// | 43 | Low             | High             | Low                | New | Negative | Energetic | **The Doom Dancer**             | Dives into dark, emotional modern hits with high energy.                                     | Crimson         |
// | 44 | Low             | High             | Low                | New | Negative | Calm      | **The Lofi Drifter**            | Enjoys mellow, sad pop playlists without fixation.                                           | Cool gray       |
// | 45 | Low             | High             | Low                | Old | Positive | Energetic | **The Retro Socialite**         | Celebrates cheerful, familiar old hits at every chance.                                      | Cherry red      |
// | 46 | Low             | High             | Low                | Old | Positive | Calm      | **The Classic Radio Fan**       | Relaxes to nostalgic radio staples and timeless tunes.                                       | Soft cream      |
// | 47 | Low             | High             | Low                | Old | Negative | Energetic | **The Torchbearer**             | Finds intensity in old heartbreak anthems; plays them loud.                                  | Wine red        |
// | 48 | Low             | High             | Low                | Old | Negative | Calm      | **The Reflective Listener**     | Quietly listens to moody old hits to feel something true.                                    | Warm gray       |
// | 49 | Low             | Low              | High               | New | Positive | Energetic | **The Minimalist Creator**      | Loyal to a few optimistic modern indie acts; keeps things simple and strong.                 | Cyan            |
// | 50 | Low             | Low              | High               | New | Positive | Calm      | **The Soft Collector**          | Attached to gentle, inspiring modern niche artists.                                          | Mint            |
// | 51 | Low             | Low              | High               | New | Negative | Energetic | **The Niche Rebel**             | Devoted to dark, intense modern underground sounds.                                          | Blood red       |
// | 52 | Low             | Low              | High               | New | Negative | Calm      | **The Shadow Follower**         | Faithful to moody modern acts with subtle emotional depth.                                   | Charcoal gray   |
// | 53 | Low             | Low              | High               | Old | Positive | Energetic | **The Revival Purist**          | Energized by obscure but uplifting classics.                                                 | Brass           |
// | 54 | Low             | Low              | High               | Old | Positive | Calm      | **The Vintage Collector**       | Treasures serene, old forgotten favorites.                                                   | Faded beige     |
// | 55 | Low             | Low              | High               | Old | Negative | Energetic | **The Obscure Devotee**         | Loyal to powerful, tragic old underground artists.                                           | Deep maroon     |
// | 56 | Low             | Low              | High               | Old | Negative | Calm      | **The Preservationist**         | Keeps a quiet connection to emotional old music.                                             | Dark brown      |
// | 57 | Low             | Low              | Low                | New | Positive | Energetic | **The Curious Casual**          | Listens lightly to cheerful modern indies; uncommitted but open.                             | Bright teal     |
// | 58 | Low             | Low              | Low                | New | Positive | Calm      | **The Gentle Dabbler**          | Occasional listener of soft, uplifting new songs.                                            | Pale blue       |
// | 59 | Low             | Low              | Low                | New | Negative | Energetic | **The Glitch Drifter**          | Dives into chaotic, dark modern sounds sporadically.                                         | Neon red        |
// | 60 | Low             | Low              | Low                | New | Negative | Calm      | **The Quiet Ghost**             | A withdrawn, infrequent listener of moody new music.                                         | Cool slate      |
// | 61 | Low             | Low              | Low                | Old | Positive | Energetic | **The Retro Casual**            | Plays light, happy old tracks occasionally for nostalgia.                                    | Apricot         |
// | 62 | Low             | Low              | Low                | Old | Positive | Calm      | **The Soft Traditionalist**     | Comforts self with gentle, familiar old music.                                               | Light beige     |
// | 63 | Low             | Low              | Low                | Old | Negative | Energetic | **The Restless Historian**      | Visits emotional corners of old music without settling long.                                 | Brick red       |
// | 64 | Low             | Low              | Low                | Old | Negative | Calm      | **The Fading Whisperer**        | Listens rarely, softly, and with longing for the past.                                       | Muted gray-blue |
